### PR TITLE
feat: add USB and dev mode commands

### PR DESCRIPTION
**Pull request by sam80180**
> Whether this PR is eventually merged or not, Sonic will thank you very much for your contribution. 
> 
> 无论此PR最终是否合并，Sonic组织都非常感谢您的贡献。

### Checklist

- [v] The title starts with fix, fea, or doc. | 标题为fix、feat或doc开头。
- [v] I have checked that there are no duplicate pull requests with this request. | 我已检查没有与此请求重复的拉取请求。
- [v] I have considered and confirmed that this submission is valuable to others. | 我已经考虑过，并确认这份呈件对其他人很有价值。
- [v] I accept that this submission may not be used. | 我接受此提交可能不会被使用。

### CODE REVIEW

**Review by ZhouYixun — COMMENTED** [review]
Nice commit, thanks for your contribution

If possible, please add our license description at the top of some important code, like here 
 https://github.com/SonicCloudOrg/sonic-ios-bridge/blob/main/cmd/afc.go

**Review by ZhouYixun — APPROVED** [review]
approve

**Comment by ZhouYixun** [comment]
I have a question, are you sure you can control the power switch of the USB port? What usbhub and operating system is it suitable for?

**Comment by sam80180** [comment]
I only tested on Linux.  😛

You can refer to this list for (possibily) compatible USB hubs (though my hubs aren't listed here, it still works):  https://github.com/mvp/uhubctl#compatible-usb-hubs

**Comment by ZhouYixun** [comment]
> I only tested on Linux. 😛
> 
> You can refer to this list for (possibily) compatible USB hubs (though my hubs aren't listed here, it still works): https://github.com/mvp/uhubctl#compatible-usb-hubs

Looks like an error occurred when compiling, maybe you need to fix it a bit

**Comment by aoliaoaoaojiao** [comment]
> I only tested on Linux. 😛
> 
> You can refer to this list for (possibily) compatible USB hubs (though my hubs aren't listed here, it still works): https://github.com/mvp/uhubctl#compatible-usb-hubs

As far as I know, there may be issues with USB on Windows. The main concept of this tool is universality, so you can separate the USB function from PR and we will place it in another branch. If users need this function, they can go to that branch on their own

**Comment by aoliaoaoaojiao** [comment]
@fossabot You may need to resubmit the PR, @ZhouYixun he hastily merged, but there are many issues that need to be determined. I will reset the master branch

**Comment by sam80180** [comment]
how about adding build tags for non-Windows systems to those USB-related files ?

**Pull request merged**
